version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "Cyb3r-Jak3"
    commit-message:
      prefix: "Action Update"
    reviewers:
      - "Cyb3r-Jak3"

  # Maintain dependencies for npm
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "Cyb3r-Jak3"
    commit-message:
      prefix: "GoMod update"
    reviewers:
      - "Cyb3r-Jak3"

  # Maintain dependencies for Composer
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "Cyb3r-Jak3"
    commit-message:
      prefix: "Docker Update"
    reviewers:
      - "Cyb3r-Jak3"