name: Build Docker

on:
  push:
    branches:
      - '**'
    tags:
     - 'v*'
    paths:
      - 'go.sum'
      - 'go.mod'
      - '**.go'
      - Dockerfile
      - .github/workflows/docker.yml

jobs:
  Docker:
    runs-on: ubuntu-latest
    
    steps:

      - name: Login To GitHub
        uses: docker/login-action@v1
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v3.7.0
        with:
          images: ghcr.io/cyb3r-jak3/stats-server
          labels: |
            org.label-schema.vcs-url=https://github.com/Cyb3r-Jak3/stats-server.git
            maintainer=Cyb3r Jak3 jake@jwhite.network
            org.opencontainers.image.vendor=cyb3rjak3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - uses: actions/checkout@v3

      - name: Build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ startsWith(github.ref, 'refs/tags/v') }}
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
